events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Docker bridge network resolver - extremely short cache for dynamic IPs
        resolver 127.0.0.11 valid=5s;

        # Disable any limits to avoid HTTP 413 for large image uploads
        client_max_body_size 0;

        # Required to avoid HTTP 411: see Issue #1486 (https://github.com/moby/moby/issues/1486)
        chunked_transfer_encoding on;

        location /v2/ {
            # Validate permissions before proxying
            auth_request /auth_check;

            proxy_pass http://registry:5000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 900;
        }

        location /npm/ {
            proxy_pass http://verdaccio:4873/;
            proxy_set_header Host            $http_host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Internal auth check endpoint
        location = /auth_check {
            internal;
            set $api_upstream_url http://api:5006/api/docker/auth_check;
            proxy_pass $api_upstream_url;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Original-Method $request_method;
            proxy_set_header Authorization $http_authorization;
        }
    }
}
